{% set name = "flake8-unused-arguments" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5b6cac6ecb325c0d5460edc6c52e2861c146eca03ddedc36dcb32beafeacbbec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flake8 >3.0.0

test:
  imports:
    - flake8_unused_arguments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nhoad/flake8-unused-arguments
  summary: flake8 extension to warn on unused function arguments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - santisoler
